- name: Gather default facts
  cisco.ios.ios_facts:
    gather_subset: min

- name: cisco api login
  ansible.builtin.uri:
    url: https://cloudsso.cisco.com/as/token.oauth2
    headers:
      Content-Type: application/x-www-form-urlencoded
    method: POST
    body:
      grant_type: client_credentials
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
    body_format: form-urlencoded
  register: ciscoapitoken
  delegate_to: localhost

- name: get psirt open vuln
  ansible.builtin.uri:
    url: https://api.cisco.com/security/advisories/{{ ansible_facts.net_iostype | lower | regex_replace("[^A-Za-z0-9]", "") }}?version={{ ansible_facts.net_version }}
    headers:
      Authorization: Bearer {{ ciscoapitoken.json.access_token }}
      Accept: application/json
    method: GET
    body_format: json
    return_content: true
  register: result
  delegate_to: localhost

- name: set fact
  ansible.builtin.set_fact:
    adv_list: "{{ result.content }}"

- name: template output
  ansible.builtin.template:
    src: report.j2
    dest: report.md

- name: append
  ansible.builtin.lineinfile:
    dest: report.md
    line: "|{{ inventory_hostname }}|{{ item.advisoryId }}| {{ item.sir }}|{{ item.cvssBaseScore }}|{{ item.firstFixed }}|"
    state: present
  loop: "{{ adv_list['advisories'] }}"
  when: "adv_list['advisories'] is defined"
  changed_when: false
  no_log: true
