---
# Gather required Data for Version, Model and os-type
- name: Gather default facts
  cisco.ios.ios_facts:
    gather_subset: min

- name: PSIRT
  ansible.builtin.import_tasks: psirt.yml
  when: psirt is true and ansible_facts.net_system == 'ios'

- name: Recommended Software
  ansible.builtin.import_tasks: rec-sw.yml
  when: recsw is true and ansible_facts.net_system == 'ios'