---
# get oauth2 token
- name: cisco api login
  ansible.builtin.uri:
    url: https://cloudsso.cisco.com/as/token.oauth2
    headers:
      Content-Type: application/x-www-form-urlencoded
    method: POST
    body:
      grant_type: client_credentials
      client_id: "{{ pss_client_id }}"
      client_secret: "{{ pss_client_secret }}"
    body_format: form-urlencoded
  register: pssciscoapitoken
  delegate_to: localhost
  run_once: true

# - name: get pid of the device
#   ansible.utils.cli_parse:
#     command: show inventory
#     parser:
#       name: ansible.netcommon.pyats
#       os: ios
#       command: show inventory
#   register: pidparsed
#   when: ansible_net_iostype == "IOS"

- name: get pid of ios-xe device
  ansible.utils.cli_parse:
    command: show inventory "Chassis"
    parser:
      name: ansible.netcommon.pyats
      os: iosxe
      command: show inventory
  register: pidparsed
  when: ansible_net_iostype == "IOS-XE"

- name: set fact
  ansible.builtin.set_fact:
    pidfact: "{{ pidparsed.parsed.main.chassis | dict2items }}"
  when: ansible_net_iostype == "IOS-XE"

- name: get PSS recommended Software for IOS-XE
  ansible.builtin.uri:
    url: https://api.cisco.com/software/suggestion/v2/suggestions/releases/productIds/{{ pidfact[0].key }}
    headers:
      Authorization: Bearer {{ pssciscoapitoken.json.access_token }}
      Accept: application/json
    method: GET
    body_format: json
    return_content: true
  register: xeresult
  delegate_to: localhost
  when: ansible_net_iostype == "IOS-XE"

- name: output
  ansible.builtin.debug:
    msg: "{{ xeresult.json.productList }}"
  when: ansible_net_iostype == "IOS-XE"

- name: get PSS recommended Software for IOS
  ansible.builtin.uri:
    url: https://api.cisco.com/software/suggestion/v2/suggestions/releases/productIds/{{ ansible_facts.net_model }}
    headers:
      Authorization: Bearer {{ pssciscoapitoken.json.access_token }}
      Accept: application/json
    method: GET
    body_format: json
    return_content: true
  register: iosresult
  delegate_to: localhost
  when: ansible_net_iostype == "IOS"

- name: output ios
  ansible.builtin.debug:
    msg: "{{ iosresult.json.productList }}"
  when: ansible_net_iostype == "IOS"